// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RentACar.Infrastructure.Data;

#nullable disable

// Place this file in: RentACar.Infrastructure\Migrations
// IMPORTANT: This is a minimal Designer file so EF can "see" the migration.
// Best practice: regenerate migrations via `dotnet ef migrations add ...` so the
// BuildTargetModel matches your real model snapshot.
namespace RentACar.Infrastructure.Migrations
{
    [DbContext(typeof(RentACarDbContext))]
    [Migration("20260304120000_AddDriverFeature")]
    public partial class AddDriverFeature
    {
       
    }
}
